trigger:
  - "master"
variables:
  buildConfiguration: "Release"
  location: "North Europe"
  acrHostName: "datacatalogregistry.azurecr.io"
  acrName: "datacatalogregistry"
  rgName: "datacatalog"
  imageName: "assets"
  webAppName: "datacatalogassethandler"

stages:
  #Build stage
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          # Create or update the ACR resource
          - task: AzureResourceGroupDeployment@2
            displayName: "Azure Deployment:Create Azure Container Registry"
            inputs:
              azureSubscription: "AzureSC"
              resourceGroupName: "$(rgName)"
              location: $(location)
              csmFile: "$(System.DefaultWorkingDirectory)/**/container-registry-template.json"
              overrideParameters: '-registryName "$(acrName)" -registryLocation "$(location)" -registrySku basic'
          - task: Gradle@2
            inputs:
              workingDirectory: ""
              gradleWrapperFile: "gradlew"
              gradleOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.11"
              jdkArchitectureOption: "x64"
              publishJUnitResults: true
              testResultsFiles: "**/TEST-*.xml"
              tasks: "assemble"
          - task: Docker@1
            displayName: "Build Container Image"
            inputs:
              azureSubscriptionEndpoint: "AzureSC"
              azureContainerRegistry: "$(acrHostName)"
              imageName: "$(imageName):$(Build.BuildId)"
              useDefaultContext: false
              buildContext: "$(System.DefaultWorkingDirectory)"
          - task: Docker@1
            displayName: "Push container image"
            inputs:
              azureSubscriptionEndpoint: "AzureSC"
              azureContainerRegistry: "$(acrHostName)"
              command: "Push an image"
              imageName: "$(imageName):$(Build.BuildId)"

          #Copy ARM templates
          - task: CopyFiles@2
            displayName: "Copy ARM templates"
            inputs:
              SourceFolder: armtemplates
              TargetFolder: "$(build.artifactstagingdirectory)"

          # Publish the app as an artifact
          - publish: $(Build.StagingDirectory)
            artifact: app
  - stage: Staging
    jobs:
      - job: Release
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: none
          - download: current
            artifact: app

            # Create or update Azure App Service
          #- task: AzureResourceGroupDeployment@2
          #  displayName: "Azure Deployment:Create Azure App Service"
          #  inputs:
          #    azureSubscription: "AzureSC"
          #    resourceGroupName: "$(rgName)"
          #    location: "$(location)"
          #    csmFile: "$(Pipeline.Workspace)/**/container-webapp-template.json"
          #    overrideParameters: '-webAppName $(webAppName) -hostingPlanName $(webAppName) -appInsightsLocation "$(location)" -sku "B1 Basic" -registryName $(acrName) -registryLocation "$(location)" -registrySku standard -imageName $(imageName):$(Build.BuildId)'

          # Deploy App Service
          - task: AzureRmWebAppDeployment@3
            displayName: "Deploy Azure App Service"
            inputs:
              azureSubscription: "AzureSC"
              appType: applinux
              WebAppName: $(webAppName)
              DockerNamespace: $(acrHostName)
              DockerRepository: $(imageName)
              DockerImageTag: "$(Build.BuildId)"
              WebAppUri: webAppUrl
              TakeAppOfflineFlag: true
              UseWebDeploy: true
              RenameFilesFlag: true
